### ISSUE TITLE
verification of 0.12.1 release not possible

### ISSUE THREAD

**Issue by dvzrv** [ValiMail/authentication-headers#1]
Hi! I'd like to package python-authheaders for Arch Linux (as I need it for mailman3).
However, the latest release 0.12.1 is missing a detached PGP signature (although former versions have this, both [on pypi](http://pypi.debian.net/authheaders) and here [on github](https://github.com/ValiMail/authentication-headers/releases)).

I know this probably happened for no bad reason, but in the light of last year's [supply chain attacks](https://en.wikipedia.org/wiki/Supply_chain_attack) on several distros and language repositories, @kitterma I'm hereby asking you to please add a PGP signature to the last release, so that downstreams can verify it.

**Comment by kitterma** [comment]
I don't think pypi will let me do that now.  If you want me to send you the signature file so you can verify it, I can do so.

**Comment by kitterma** [comment]
0.12.2 is uploaded to both github and pypi with the signature file, so that should resolve this issue.
