### ISSUE TITLE
Put notice in README that Python v3.6+ is required

### ISSUE THREAD

**Issue by niftylettuce** [ValiMail/authentication-headers#11]
I wasn't able to get Travis to build unless I either upgraded from xenial to bionic (which put my version to 3.6), or manually used pyenv command on xenial to upgrade from v3.5 to v3.6.

https://travis-ci.com/github/forwardemail/authheaders (see build history)

**Comment by kitterma** [comment]
Do you remember what the actual issue was?  I can't see it in the build history now and I don't recall anything we have in this that actually needs python3.6.  Probably no one cares much about this anymore.

**Comment by niftylettuce** [comment]
See <https://github.com/ValiMail/authentication-headers/issues/19#issuecomment-1014955652> for closing comment.
