### ISSUE TITLE
Unknown license

### ISSUE THREAD

**Issue by dvzrv** [ValiMail/authentication-headers#24]
Hi! I'm packaging this project for Arch Linux.

As we are now supporting the use of SPDX license identifiers (https://spdx.org/licenses/), I'm trying to find out what is the license identifier for this license: https://github.com/ValiMail/authentication-headers/blob/05ff686bb5916c1d3435cd06294d21b66a7fc91f/COPYING#L2-L19

Maybe you can help me figure this out? :)

**Comment by kitterma** [comment]
Zlib.

https://opensource.org/license/zlib/

**Comment by dvzrv** [comment]
Ah, awesome! Thanks for clarifying this so fast.
It seems like many downstreams wrongly classified this as MIT or BSD-3-Clause.

It could potentially be helpful for others if this was made more explicit! Thanks either way! :)
