### ISSUE TITLE
DKIM signing fails

### ISSUE THREAD

**Issue by adam-iris** [ValiMail/authentication-headers#3]
Trying to sign a message with DKIM, I get this error:

> TypeError: sign() got an unexpected keyword argument 'timestamp'

Looking at `dkimpy` this seems like a valid error -- `ARC.sign()` takes a "timestamp" parameter but `DKIM.sign()` doesn't.

**Comment by kitterma** [comment]
Agreed.  Should be easy enough to fix.  Thanks.

**Comment by kitterma** [comment]
Fixed in https://github.com/ValiMail/authentication-headers/commit/953faf8dd7a5e81f81943a6789a875a6555551b0 .
